// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: ChargerStation

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// SCREEN: ui_MainScreen
void ui_MainScreen_screen_init(void);
lv_obj_t *ui_MainScreen;
lv_obj_t *ui_MainHeader;
lv_obj_t *ui_HeaderUSBC;
lv_obj_t *ui_HeaderUSBA;
void ui_event_USBCSwitch( lv_event_t * e);
lv_obj_t *ui_USBCSwitch;
void ui_event_USBASwitch( lv_event_t * e);
lv_obj_t *ui_USBASwitch;
void ui_event_Setting( lv_event_t * e);
lv_obj_t *ui_Setting;
lv_obj_t *ui_ImageSetting;
void ui_event_Weather( lv_event_t * e);
lv_obj_t *ui_Weather;
lv_obj_t *ui_ImageWeather;
lv_obj_t *ui_InformationDock;
lv_obj_t *ui_Voltage;
lv_obj_t *ui_TextU;
lv_obj_t *ui_TextV;
lv_obj_t *ui_Current;
lv_obj_t *ui_TextI;
lv_obj_t *ui_TextA;
lv_obj_t *ui_Power;
lv_obj_t *ui_TextP;
lv_obj_t *ui_TextW;
lv_obj_t *ui_ImageWiFi;
lv_obj_t *ui_Hour;
lv_obj_t *ui_Minute;
lv_obj_t *ui_Second;
lv_obj_t *ui_TextHM;
lv_obj_t *ui_TextMS;
lv_obj_t *ui_USBADock;
lv_obj_t *ui_ImageUSBA;
lv_obj_t *ui_VoltageUSBA;
lv_obj_t *ui_USBC3Dock;
lv_obj_t *ui_ImageUSBC3;
lv_obj_t *ui_VoltageUSBC3;
lv_obj_t *ui_USBC2Dock;
lv_obj_t *ui_ImageUSBC2;
lv_obj_t *ui_ImageUSBC2Fast;
lv_obj_t *ui_VoltageUSBC2;
lv_obj_t *ui_USBC1Dock;
lv_obj_t *ui_ImageUSBC1;
lv_obj_t *ui_ImageUSBC1Fast;
lv_obj_t *ui_VoltageUSBC1;
// CUSTOM VARIABLES

// SCREEN: ui_SettingScreen
void ui_SettingScreen_screen_init(void);
lv_obj_t *ui_SettingScreen;
lv_obj_t *ui_SettingHeader;
lv_obj_t *ui_TextSettingHeader;
lv_obj_t *ui_FreeSpace;
lv_obj_t *ui_SettingDock;
void ui_event_WiFiWebPage( lv_event_t * e);
lv_obj_t *ui_WiFiWebPage;
lv_obj_t *ui_ImageWiFiWebPage;
lv_obj_t *ui_TextWiFiWebPage;
void ui_event_ADCAdjust( lv_event_t * e);
lv_obj_t *ui_ADCAdjust;
lv_obj_t *ui_ImageADCAdjust;
lv_obj_t *ui_TextADCAdjust;
lv_obj_t *ui_PanelFanSwitch;
lv_obj_t *ui_ImageFanSwitch;
lv_obj_t *ui_TextFanSwitch;
void ui_event_FanSwitch( lv_event_t * e);
lv_obj_t *ui_FanSwitch;
void ui_event_SliderSleepTime( lv_event_t * e);
lv_obj_t *ui_SliderSleepTime;
lv_obj_t *ui_ImageSleepTime;
lv_obj_t *ui_SleepTime;
void ui_event_SliderBrightness( lv_event_t * e);
lv_obj_t *ui_SliderBrightness;
lv_obj_t *ui_ImageBrightness;
lv_obj_t *ui_Brightness;
void ui_event_Back( lv_event_t * e);
lv_obj_t *ui_Back;
lv_obj_t *ui_TextBack;
// CUSTOM VARIABLES

// SCREEN: ui_ADCAdjustScreen
void ui_ADCAdjustScreen_screen_init(void);
lv_obj_t *ui_ADCAdjustScreen;
lv_obj_t *ui_ADCHeader;
lv_obj_t *ui_TextADCHeader;
lv_obj_t *ui_ADCAdjustDock;
void ui_event_USBAAdjust( lv_event_t * e);
lv_obj_t *ui_USBAAdjust;
lv_obj_t *ui_ImageUSBAAdjust;
lv_obj_t *ui_VoltageUSBAADC;
void ui_event_USBC3Adjust( lv_event_t * e);
lv_obj_t *ui_USBC3Adjust;
lv_obj_t *ui_ImageUSBC3Adjust;
lv_obj_t *ui_VoltageUSBC3ADC;
void ui_event_USBC2Adjust( lv_event_t * e);
lv_obj_t *ui_USBC2Adjust;
lv_obj_t *ui_ImageUSBC2Adjust;
lv_obj_t *ui_ImageUSBC3AdjustB;
lv_obj_t *ui_VoltageUSBC2ADC;
void ui_event_USBC1Adjust( lv_event_t * e);
lv_obj_t *ui_USBC1Adjust;
lv_obj_t *ui_ImageUSBC1Adjust;
lv_obj_t *ui_ImageUSBC3AdjustB1;
lv_obj_t *ui_VoltageUSBC1ADC;
void ui_event_ADCBack( lv_event_t * e);
lv_obj_t *ui_ADCBack;
lv_obj_t *ui_TextADCBack;
// CUSTOM VARIABLES

// SCREEN: ui_WiFiScreen
void ui_WiFiScreen_screen_init(void);
lv_obj_t *ui_WiFiScreen;
lv_obj_t *ui_WIFIHeader;
lv_obj_t *ui_TextWIFIHeader;
void ui_event_WIFIBack( lv_event_t * e);
lv_obj_t *ui_WIFIBack;
lv_obj_t *ui_TextWIFIBack;
lv_obj_t *ui_WIFISettingDock;
void ui_event_WIFIStart( lv_event_t * e);
lv_obj_t *ui_WIFIStart;
lv_obj_t *ui_TextWIFIStart;
void ui_event_WIFIReset( lv_event_t * e);
lv_obj_t *ui_WIFIReset;
lv_obj_t *ui_TextWIFIReset;
lv_obj_t *ui_WIFIStatus;
lv_obj_t *ui_TEXTSSID;
lv_obj_t *ui_SSID;
lv_obj_t *ui_TEXTIP;
lv_obj_t *ui_IPADDR;
lv_obj_t *ui_TEXTSYNCTIME;
lv_obj_t *ui_SYNCTIME;
// CUSTOM VARIABLES

// SCREEN: ui_WeatherScreen
void ui_WeatherScreen_screen_init(void);
lv_obj_t *ui_WeatherScreen;
void ui_event_WeatherBack( lv_event_t * e);
lv_obj_t *ui_WeatherBack;
lv_obj_t *ui_TextWeatherBack;
void ui_event_WeatherSetting( lv_event_t * e);
lv_obj_t *ui_WeatherSetting;
lv_obj_t *ui_TextWeatherSetting;
lv_obj_t *ui_WeatherDock;
lv_obj_t *ui_ImageTemp;
lv_obj_t *ui_ImageHumi;
lv_obj_t *ui_Humidity;
lv_obj_t *ui_Temperature;
lv_obj_t *ui_WeatherPanel;
lv_obj_t *ui_WeatherICON;
lv_obj_t *ui_Week;
lv_obj_t *ui_WheatherCHN0Panel;
lv_obj_t *ui_WeatherCHN;
lv_obj_t *ui_TimeDock;
lv_obj_t *ui_TextWTime;
lv_obj_t *ui_WHour;
lv_obj_t *ui_WMinute;
lv_obj_t *ui_WSecond;
lv_obj_t *ui_WPowerDock;
lv_obj_t *ui_TextWVoltage;
lv_obj_t *ui_WVoltage;
lv_obj_t *ui_TextWCurrent;
lv_obj_t *ui_WCurrent;
lv_obj_t *ui_TextWPower;
lv_obj_t *ui_WPower;
// CUSTOM VARIABLES

// EVENTS
lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init( void )
{
lv_disp_t *dispp = lv_disp_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), true, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);
ui_MainScreen_screen_init();
ui_SettingScreen_screen_init();
ui_ADCAdjustScreen_screen_init();
ui_WiFiScreen_screen_init();
ui_WeatherScreen_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
lv_disp_load_scr( ui_MainScreen);
}
