// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: ChargerStation

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void USBCPowerON(lv_event_t * e);
void USBCPowerOFF(lv_event_t * e);
void USBAPowerON(lv_event_t * e);
void USBAPowerOFF(lv_event_t * e);
void FanSwitchON(lv_event_t * e);
void FanSwitchOFF(lv_event_t * e);
void USBAAdjust(lv_event_t * e);
void USBC3Adjust(lv_event_t * e);
void USBC2Adjust(lv_event_t * e);
void USBC1Adjust(lv_event_t * e);
void WIFIStart(lv_event_t * e);
void WIFIResrt(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
