// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: ChargerStation

#include "ui.h"

void USBCPowerON(lv_event_t * e)
{
	// Your code here
}

void USBCPowerOFF(lv_event_t * e)
{
	// Your code here
}

void USBAPowerON(lv_event_t * e)
{
	// Your code here
}

void USBAPowerOFF(lv_event_t * e)
{
	// Your code here
}

void FanSwitchON(lv_event_t * e)
{
	// Your code here
}

void FanSwitchOFF(lv_event_t * e)
{
	// Your code here
}

void PwControlON(lv_event_t * e)
{
	// Your code here
}

void PwControlOFF(lv_event_t * e)
{
	// Your code here
}

void USBAAdjust(lv_event_t * e)
{
	// Your code here
}

void USBC3Adjust(lv_event_t * e)
{
	// Your code here
}

void USBC2Adjust(lv_event_t * e)
{
	// Your code here
}

void USBC1Adjust(lv_event_t * e)
{
	// Your code here
}

void WIFIResrt(lv_event_t * e)
{
	// Your code here
}

void WIFIStart(lv_event_t * e)
{
	// Your code here
}
