// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: ChargerStation

#include "../ui.h"

void ui_ADCAdjustScreen_screen_init(void)
{
ui_ADCAdjustScreen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_ADCAdjustScreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_ADCAdjustScreen, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_Text_Switch);
ui_object_set_themeable_style_property(ui_ADCAdjustScreen, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_Text_Switch);

ui_ADCHeader = lv_obj_create(ui_ADCAdjustScreen);
lv_obj_remove_style_all(ui_ADCHeader);
lv_obj_set_width( ui_ADCHeader, 236);
lv_obj_set_height( ui_ADCHeader, 32);
lv_obj_set_x( ui_ADCHeader, 0 );
lv_obj_set_y( ui_ADCHeader, 2 );
lv_obj_set_align( ui_ADCHeader, LV_ALIGN_TOP_MID );
lv_obj_clear_flag( ui_ADCHeader, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_ADCHeader, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_ADCHeader, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_Container);
ui_object_set_themeable_style_property(ui_ADCHeader, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_Container);

ui_TextADCHeader = lv_label_create(ui_ADCHeader);
lv_obj_set_width( ui_TextADCHeader, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_TextADCHeader, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_TextADCHeader, LV_ALIGN_CENTER );
lv_label_set_text(ui_TextADCHeader,"接口电压校准");
ui_object_set_themeable_style_property(ui_TextADCHeader, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_Text_Switch);
ui_object_set_themeable_style_property(ui_TextADCHeader, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_Text_Switch);
lv_obj_set_style_text_font(ui_TextADCHeader, &ui_font_ASCII20MONO, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ADCAdjustDock = lv_obj_create(ui_ADCAdjustScreen);
lv_obj_remove_style_all(ui_ADCAdjustDock);
lv_obj_set_width( ui_ADCAdjustDock, 236);
lv_obj_set_height( ui_ADCAdjustDock, 172);
lv_obj_set_x( ui_ADCAdjustDock, 0 );
lv_obj_set_y( ui_ADCAdjustDock, 38 );
lv_obj_set_align( ui_ADCAdjustDock, LV_ALIGN_TOP_MID );
lv_obj_set_flex_flow(ui_ADCAdjustDock,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_ADCAdjustDock, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_ADCAdjustDock, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_ADCAdjustDock, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_ADCAdjustDock, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_Container);
ui_object_set_themeable_style_property(ui_ADCAdjustDock, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_Container);

ui_USBAAdjust = lv_slider_create(ui_ADCAdjustDock);
lv_slider_set_range(ui_USBAAdjust, 850,1250);
lv_slider_set_value( ui_USBAAdjust, 1085, LV_ANIM_OFF);
if (lv_slider_get_mode(ui_USBAAdjust)==LV_SLIDER_MODE_RANGE ) lv_slider_set_left_value( ui_USBAAdjust, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_USBAAdjust, 228);
lv_obj_set_height( ui_USBAAdjust, 28);
lv_obj_set_x( ui_USBAAdjust, 0 );
lv_obj_set_y( ui_USBAAdjust, 4 );
lv_obj_set_align( ui_USBAAdjust, LV_ALIGN_TOP_MID );
lv_obj_set_style_radius(ui_USBAAdjust, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_USBAAdjust, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_BG_Button);
ui_object_set_themeable_style_property(ui_USBAAdjust, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_BG_Button);
ui_object_set_themeable_style_property(ui_USBAAdjust, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_OUTLINE_COLOR, _ui_theme_color_BG_Button);
ui_object_set_themeable_style_property(ui_USBAAdjust, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_OUTLINE_OPA, _ui_theme_alpha_BG_Button);
lv_obj_set_style_outline_width(ui_USBAAdjust, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_pad(ui_USBAAdjust, 1, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_radius(ui_USBAAdjust, 5, LV_PART_INDICATOR| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_USBAAdjust, LV_PART_INDICATOR| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_Container);
ui_object_set_themeable_style_property(ui_USBAAdjust, LV_PART_INDICATOR| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_Container);

lv_obj_set_style_bg_color(ui_USBAAdjust, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_USBAAdjust, 0, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_ImageUSBAAdjust = lv_img_create(ui_USBAAdjust);
lv_img_set_src(ui_ImageUSBAAdjust, &ui_img_2092987087);
lv_obj_set_width( ui_ImageUSBAAdjust, LV_SIZE_CONTENT);  /// 32
lv_obj_set_height( ui_ImageUSBAAdjust, LV_SIZE_CONTENT);   /// 32
lv_obj_set_x( ui_ImageUSBAAdjust, 5 );
lv_obj_set_y( ui_ImageUSBAAdjust, 0 );
lv_obj_set_align( ui_ImageUSBAAdjust, LV_ALIGN_LEFT_MID );
lv_obj_add_flag( ui_ImageUSBAAdjust, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ImageUSBAAdjust, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_ImageUSBAAdjust,230);

ui_VoltageUSBAADC = lv_label_create(ui_USBAAdjust);
lv_obj_set_width( ui_VoltageUSBAADC, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_VoltageUSBAADC, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_VoltageUSBAADC, -10 );
lv_obj_set_y( ui_VoltageUSBAADC, 0 );
lv_obj_set_align( ui_VoltageUSBAADC, LV_ALIGN_RIGHT_MID );
lv_label_set_text(ui_VoltageUSBAADC,"00.0V");
ui_object_set_themeable_style_property(ui_VoltageUSBAADC, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_Text_Switch);
ui_object_set_themeable_style_property(ui_VoltageUSBAADC, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_Text_Switch);
lv_obj_set_style_text_font(ui_VoltageUSBAADC, &ui_font_ASCII20MONO, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_USBC3Adjust = lv_slider_create(ui_ADCAdjustDock);
lv_slider_set_range(ui_USBC3Adjust, 850,1250);
lv_slider_set_value( ui_USBC3Adjust, 1085, LV_ANIM_OFF);
if (lv_slider_get_mode(ui_USBC3Adjust)==LV_SLIDER_MODE_RANGE ) lv_slider_set_left_value( ui_USBC3Adjust, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_USBC3Adjust, 228);
lv_obj_set_height( ui_USBC3Adjust, 28);
lv_obj_set_x( ui_USBC3Adjust, 0 );
lv_obj_set_y( ui_USBC3Adjust, 38 );
lv_obj_set_align( ui_USBC3Adjust, LV_ALIGN_TOP_MID );
lv_obj_set_style_radius(ui_USBC3Adjust, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_USBC3Adjust, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_BG_Button);
ui_object_set_themeable_style_property(ui_USBC3Adjust, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_BG_Button);
ui_object_set_themeable_style_property(ui_USBC3Adjust, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_OUTLINE_COLOR, _ui_theme_color_BG_Button);
ui_object_set_themeable_style_property(ui_USBC3Adjust, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_OUTLINE_OPA, _ui_theme_alpha_BG_Button);
lv_obj_set_style_outline_width(ui_USBC3Adjust, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_pad(ui_USBC3Adjust, 1, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_radius(ui_USBC3Adjust, 5, LV_PART_INDICATOR| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_USBC3Adjust, LV_PART_INDICATOR| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_Container);
ui_object_set_themeable_style_property(ui_USBC3Adjust, LV_PART_INDICATOR| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_Container);

lv_obj_set_style_bg_color(ui_USBC3Adjust, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_USBC3Adjust, 0, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_ImageUSBC3Adjust = lv_img_create(ui_USBC3Adjust);
lv_img_set_src(ui_ImageUSBC3Adjust, &ui_img_426970754);
lv_obj_set_width( ui_ImageUSBC3Adjust, LV_SIZE_CONTENT);  /// 32
lv_obj_set_height( ui_ImageUSBC3Adjust, LV_SIZE_CONTENT);   /// 32
lv_obj_set_x( ui_ImageUSBC3Adjust, 5 );
lv_obj_set_y( ui_ImageUSBC3Adjust, 0 );
lv_obj_set_align( ui_ImageUSBC3Adjust, LV_ALIGN_LEFT_MID );
lv_obj_add_flag( ui_ImageUSBC3Adjust, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ImageUSBC3Adjust, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_ImageUSBC3Adjust,230);

ui_VoltageUSBC3ADC = lv_label_create(ui_USBC3Adjust);
lv_obj_set_width( ui_VoltageUSBC3ADC, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_VoltageUSBC3ADC, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_VoltageUSBC3ADC, -10 );
lv_obj_set_y( ui_VoltageUSBC3ADC, 0 );
lv_obj_set_align( ui_VoltageUSBC3ADC, LV_ALIGN_RIGHT_MID );
lv_label_set_text(ui_VoltageUSBC3ADC,"00.0V");
ui_object_set_themeable_style_property(ui_VoltageUSBC3ADC, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_Text_Switch);
ui_object_set_themeable_style_property(ui_VoltageUSBC3ADC, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_Text_Switch);
lv_obj_set_style_text_font(ui_VoltageUSBC3ADC, &ui_font_ASCII20MONO, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_USBC2Adjust = lv_slider_create(ui_ADCAdjustDock);
lv_slider_set_range(ui_USBC2Adjust, 850,1250);
lv_slider_set_value( ui_USBC2Adjust, 1085, LV_ANIM_OFF);
if (lv_slider_get_mode(ui_USBC2Adjust)==LV_SLIDER_MODE_RANGE ) lv_slider_set_left_value( ui_USBC2Adjust, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_USBC2Adjust, 228);
lv_obj_set_height( ui_USBC2Adjust, 28);
lv_obj_set_x( ui_USBC2Adjust, 0 );
lv_obj_set_y( ui_USBC2Adjust, 72 );
lv_obj_set_align( ui_USBC2Adjust, LV_ALIGN_TOP_MID );
lv_obj_set_style_radius(ui_USBC2Adjust, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_USBC2Adjust, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_BG_Button);
ui_object_set_themeable_style_property(ui_USBC2Adjust, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_BG_Button);
ui_object_set_themeable_style_property(ui_USBC2Adjust, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_OUTLINE_COLOR, _ui_theme_color_BG_Button);
ui_object_set_themeable_style_property(ui_USBC2Adjust, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_OUTLINE_OPA, _ui_theme_alpha_BG_Button);
lv_obj_set_style_outline_width(ui_USBC2Adjust, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_pad(ui_USBC2Adjust, 1, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_radius(ui_USBC2Adjust, 5, LV_PART_INDICATOR| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_USBC2Adjust, LV_PART_INDICATOR| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_Container);
ui_object_set_themeable_style_property(ui_USBC2Adjust, LV_PART_INDICATOR| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_Container);

lv_obj_set_style_bg_color(ui_USBC2Adjust, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_USBC2Adjust, 0, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_ImageUSBC2Adjust = lv_img_create(ui_USBC2Adjust);
lv_img_set_src(ui_ImageUSBC2Adjust, &ui_img_426970754);
lv_obj_set_width( ui_ImageUSBC2Adjust, LV_SIZE_CONTENT);  /// 32
lv_obj_set_height( ui_ImageUSBC2Adjust, LV_SIZE_CONTENT);   /// 32
lv_obj_set_x( ui_ImageUSBC2Adjust, 5 );
lv_obj_set_y( ui_ImageUSBC2Adjust, 0 );
lv_obj_set_align( ui_ImageUSBC2Adjust, LV_ALIGN_LEFT_MID );
lv_obj_add_flag( ui_ImageUSBC2Adjust, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ImageUSBC2Adjust, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_ImageUSBC2Adjust,230);

ui_ImageUSBC3AdjustB = lv_img_create(ui_USBC2Adjust);
lv_img_set_src(ui_ImageUSBC3AdjustB, &ui_img_175199537);
lv_obj_set_width( ui_ImageUSBC3AdjustB, LV_SIZE_CONTENT);  /// 32
lv_obj_set_height( ui_ImageUSBC3AdjustB, LV_SIZE_CONTENT);   /// 32
lv_obj_set_x( ui_ImageUSBC3AdjustB, 35 );
lv_obj_set_y( ui_ImageUSBC3AdjustB, 0 );
lv_obj_set_align( ui_ImageUSBC3AdjustB, LV_ALIGN_LEFT_MID );
lv_obj_add_flag( ui_ImageUSBC3AdjustB, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ImageUSBC3AdjustB, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_ImageUSBC3AdjustB,230);

ui_VoltageUSBC2ADC = lv_label_create(ui_USBC2Adjust);
lv_obj_set_width( ui_VoltageUSBC2ADC, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_VoltageUSBC2ADC, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_VoltageUSBC2ADC, -10 );
lv_obj_set_y( ui_VoltageUSBC2ADC, 0 );
lv_obj_set_align( ui_VoltageUSBC2ADC, LV_ALIGN_RIGHT_MID );
lv_label_set_text(ui_VoltageUSBC2ADC,"00.0V");
ui_object_set_themeable_style_property(ui_VoltageUSBC2ADC, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_Text_Switch);
ui_object_set_themeable_style_property(ui_VoltageUSBC2ADC, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_Text_Switch);
lv_obj_set_style_text_font(ui_VoltageUSBC2ADC, &ui_font_ASCII20MONO, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_USBC1Adjust = lv_slider_create(ui_ADCAdjustDock);
lv_slider_set_range(ui_USBC1Adjust, 850,1250);
lv_slider_set_value( ui_USBC1Adjust, 1085, LV_ANIM_OFF);
if (lv_slider_get_mode(ui_USBC1Adjust)==LV_SLIDER_MODE_RANGE ) lv_slider_set_left_value( ui_USBC1Adjust, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_USBC1Adjust, 228);
lv_obj_set_height( ui_USBC1Adjust, 28);
lv_obj_set_x( ui_USBC1Adjust, 0 );
lv_obj_set_y( ui_USBC1Adjust, 106 );
lv_obj_set_align( ui_USBC1Adjust, LV_ALIGN_TOP_MID );
lv_obj_set_style_radius(ui_USBC1Adjust, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_USBC1Adjust, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_BG_Button);
ui_object_set_themeable_style_property(ui_USBC1Adjust, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_BG_Button);
ui_object_set_themeable_style_property(ui_USBC1Adjust, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_OUTLINE_COLOR, _ui_theme_color_BG_Button);
ui_object_set_themeable_style_property(ui_USBC1Adjust, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_OUTLINE_OPA, _ui_theme_alpha_BG_Button);
lv_obj_set_style_outline_width(ui_USBC1Adjust, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_pad(ui_USBC1Adjust, 1, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_radius(ui_USBC1Adjust, 5, LV_PART_INDICATOR| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_USBC1Adjust, LV_PART_INDICATOR| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_Container);
ui_object_set_themeable_style_property(ui_USBC1Adjust, LV_PART_INDICATOR| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_Container);

lv_obj_set_style_bg_color(ui_USBC1Adjust, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_USBC1Adjust, 0, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_ImageUSBC1Adjust = lv_img_create(ui_USBC1Adjust);
lv_img_set_src(ui_ImageUSBC1Adjust, &ui_img_426970754);
lv_obj_set_width( ui_ImageUSBC1Adjust, LV_SIZE_CONTENT);  /// 32
lv_obj_set_height( ui_ImageUSBC1Adjust, LV_SIZE_CONTENT);   /// 32
lv_obj_set_x( ui_ImageUSBC1Adjust, 5 );
lv_obj_set_y( ui_ImageUSBC1Adjust, 0 );
lv_obj_set_align( ui_ImageUSBC1Adjust, LV_ALIGN_LEFT_MID );
lv_obj_add_flag( ui_ImageUSBC1Adjust, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ImageUSBC1Adjust, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_ImageUSBC1Adjust,230);

ui_ImageUSBC3AdjustB1 = lv_img_create(ui_USBC1Adjust);
lv_img_set_src(ui_ImageUSBC3AdjustB1, &ui_img_175199537);
lv_obj_set_width( ui_ImageUSBC3AdjustB1, LV_SIZE_CONTENT);  /// 32
lv_obj_set_height( ui_ImageUSBC3AdjustB1, LV_SIZE_CONTENT);   /// 32
lv_obj_set_x( ui_ImageUSBC3AdjustB1, 35 );
lv_obj_set_y( ui_ImageUSBC3AdjustB1, 0 );
lv_obj_set_align( ui_ImageUSBC3AdjustB1, LV_ALIGN_LEFT_MID );
lv_obj_add_flag( ui_ImageUSBC3AdjustB1, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ImageUSBC3AdjustB1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_ImageUSBC3AdjustB1,230);

ui_VoltageUSBC1ADC = lv_label_create(ui_USBC1Adjust);
lv_obj_set_width( ui_VoltageUSBC1ADC, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_VoltageUSBC1ADC, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_VoltageUSBC1ADC, -10 );
lv_obj_set_y( ui_VoltageUSBC1ADC, 0 );
lv_obj_set_align( ui_VoltageUSBC1ADC, LV_ALIGN_RIGHT_MID );
lv_label_set_text(ui_VoltageUSBC1ADC,"00.0V");
ui_object_set_themeable_style_property(ui_VoltageUSBC1ADC, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_Text_Switch);
ui_object_set_themeable_style_property(ui_VoltageUSBC1ADC, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_Text_Switch);
lv_obj_set_style_text_font(ui_VoltageUSBC1ADC, &ui_font_ASCII20MONO, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ADCBack = lv_btn_create(ui_ADCAdjustScreen);
lv_obj_set_width( ui_ADCBack, 236);
lv_obj_set_height( ui_ADCBack, 24);
lv_obj_set_x( ui_ADCBack, 0 );
lv_obj_set_y( ui_ADCBack, -2 );
lv_obj_set_align( ui_ADCBack, LV_ALIGN_BOTTOM_MID );
lv_obj_add_flag( ui_ADCBack, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ADCBack, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_ADCBack, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_BG_Button);
ui_object_set_themeable_style_property(ui_ADCBack, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_BG_Button);

ui_TextADCBack = lv_label_create(ui_ADCBack);
lv_obj_set_width( ui_TextADCBack, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_TextADCBack, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_TextADCBack, LV_ALIGN_CENTER );
lv_label_set_text(ui_TextADCBack,"返回");
ui_object_set_themeable_style_property(ui_TextADCBack, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_Text_Switch);
ui_object_set_themeable_style_property(ui_TextADCBack, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_Text_Switch);
lv_obj_set_style_text_font(ui_TextADCBack, &ui_font_ASCII20MONO, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_USBAAdjust, ui_event_USBAAdjust, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_USBC3Adjust, ui_event_USBC3Adjust, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_USBC2Adjust, ui_event_USBC2Adjust, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_USBC1Adjust, ui_event_USBC1Adjust, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ADCBack, ui_event_ADCBack, LV_EVENT_ALL, NULL);

}
