// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: ChargerStation

#include "../ui.h"

void ui_MainScreen_screen_init(void)
{
ui_MainScreen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_MainScreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_MainScreen, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_Text_Switch);
ui_object_set_themeable_style_property(ui_MainScreen, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_Text_Switch);

ui_MainHeader = lv_obj_create(ui_MainScreen);
lv_obj_remove_style_all(ui_MainHeader);
lv_obj_set_width( ui_MainHeader, 236);
lv_obj_set_height( ui_MainHeader, 32);
lv_obj_set_x( ui_MainHeader, 0 );
lv_obj_set_y( ui_MainHeader, 2 );
lv_obj_set_align( ui_MainHeader, LV_ALIGN_TOP_MID );
lv_obj_clear_flag( ui_MainHeader, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_MainHeader, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_MainHeader, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_Container);
ui_object_set_themeable_style_property(ui_MainHeader, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_Container);

ui_HeaderUSBC = lv_img_create(ui_MainHeader);
lv_img_set_src(ui_HeaderUSBC, &ui_img_426970754);
lv_obj_set_width( ui_HeaderUSBC, LV_SIZE_CONTENT);  /// 32
lv_obj_set_height( ui_HeaderUSBC, LV_SIZE_CONTENT);   /// 32
lv_obj_set_x( ui_HeaderUSBC, 5 );
lv_obj_set_y( ui_HeaderUSBC, -1 );
lv_obj_set_align( ui_HeaderUSBC, LV_ALIGN_LEFT_MID );
lv_obj_add_flag( ui_HeaderUSBC, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_HeaderUSBC, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_HeaderUSBA = lv_img_create(ui_MainHeader);
lv_img_set_src(ui_HeaderUSBA, &ui_img_2092987087);
lv_obj_set_width( ui_HeaderUSBA, LV_SIZE_CONTENT);  /// 32
lv_obj_set_height( ui_HeaderUSBA, LV_SIZE_CONTENT);   /// 32
lv_obj_set_x( ui_HeaderUSBA, 80 );
lv_obj_set_y( ui_HeaderUSBA, 0 );
lv_obj_set_align( ui_HeaderUSBA, LV_ALIGN_LEFT_MID );
lv_obj_add_flag( ui_HeaderUSBA, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_HeaderUSBA, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_USBCSwitch = lv_switch_create(ui_MainHeader);
lv_obj_set_width( ui_USBCSwitch, 30);
lv_obj_set_height( ui_USBCSwitch, 16);
lv_obj_set_x( ui_USBCSwitch, 44 );
lv_obj_set_y( ui_USBCSwitch, 0 );
lv_obj_set_align( ui_USBCSwitch, LV_ALIGN_LEFT_MID );
ui_object_set_themeable_style_property(ui_USBCSwitch, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_Text_Switch);
ui_object_set_themeable_style_property(ui_USBCSwitch, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_Text_Switch);

lv_obj_set_style_bg_color(ui_USBCSwitch, lv_color_hex(0x00FF00), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_USBCSwitch, 255, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_USBASwitch = lv_switch_create(ui_MainHeader);
lv_obj_set_width( ui_USBASwitch, 30);
lv_obj_set_height( ui_USBASwitch, 16);
lv_obj_set_x( ui_USBASwitch, 120 );
lv_obj_set_y( ui_USBASwitch, 0 );
lv_obj_set_align( ui_USBASwitch, LV_ALIGN_LEFT_MID );
ui_object_set_themeable_style_property(ui_USBASwitch, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_Text_Switch);
ui_object_set_themeable_style_property(ui_USBASwitch, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_Text_Switch);

lv_obj_set_style_bg_color(ui_USBASwitch, lv_color_hex(0x00FF00), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_USBASwitch, 255, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_Setting = lv_btn_create(ui_MainHeader);
lv_obj_set_width( ui_Setting, 32);
lv_obj_set_height( ui_Setting, 28);
lv_obj_set_x( ui_Setting, -2 );
lv_obj_set_y( ui_Setting, 0 );
lv_obj_set_align( ui_Setting, LV_ALIGN_RIGHT_MID );
lv_obj_add_flag( ui_Setting, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Setting, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Setting, lv_color_hex(0x00FFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Setting, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ImageSetting = lv_img_create(ui_Setting);
lv_img_set_src(ui_ImageSetting, &ui_img_1671917170);
lv_obj_set_width( ui_ImageSetting, LV_SIZE_CONTENT);  /// 32
lv_obj_set_height( ui_ImageSetting, LV_SIZE_CONTENT);   /// 32
lv_obj_set_align( ui_ImageSetting, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ImageSetting, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ImageSetting, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_angle(ui_ImageSetting,300);

ui_Weather = lv_btn_create(ui_MainHeader);
lv_obj_set_width( ui_Weather, 32);
lv_obj_set_height( ui_Weather, 28);
lv_obj_set_x( ui_Weather, -40 );
lv_obj_set_y( ui_Weather, 0 );
lv_obj_set_align( ui_Weather, LV_ALIGN_RIGHT_MID );
lv_obj_add_flag( ui_Weather, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Weather, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Weather, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Weather, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ImageWeather = lv_img_create(ui_Weather);
lv_img_set_src(ui_ImageWeather, &ui_img_1222334931);
lv_obj_set_width( ui_ImageWeather, LV_SIZE_CONTENT);  /// 32
lv_obj_set_height( ui_ImageWeather, LV_SIZE_CONTENT);   /// 32
lv_obj_set_align( ui_ImageWeather, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ImageWeather, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ImageWeather, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_InformationDock = lv_obj_create(ui_MainScreen);
lv_obj_remove_style_all(ui_InformationDock);
lv_obj_set_width( ui_InformationDock, 168);
lv_obj_set_height( ui_InformationDock, 200);
lv_obj_set_x( ui_InformationDock, -2 );
lv_obj_set_y( ui_InformationDock, 38 );
lv_obj_set_align( ui_InformationDock, LV_ALIGN_TOP_RIGHT );
lv_obj_clear_flag( ui_InformationDock, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_InformationDock, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_InformationDock, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_Container);
ui_object_set_themeable_style_property(ui_InformationDock, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_Container);

ui_Voltage = lv_label_create(ui_InformationDock);
lv_obj_set_width( ui_Voltage, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Voltage, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Voltage, 2 );
lv_obj_set_y( ui_Voltage, -76 );
lv_obj_set_align( ui_Voltage, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_Voltage,"00.00");
lv_obj_set_style_text_color(ui_Voltage, lv_color_hex(0xFF7D00), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Voltage, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Voltage, &ui_font_ASCII40MONO, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_Voltage, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_Voltage, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_Text_Switch);
ui_object_set_themeable_style_property(ui_Voltage, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_Text_Switch);
lv_obj_set_style_border_color(ui_Voltage, lv_color_hex(0xFF7D00), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Voltage, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Voltage, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_Voltage, 32, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Voltage, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Voltage, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Voltage, -3, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TextU = lv_label_create(ui_Voltage);
lv_obj_set_width( ui_TextU, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_TextU, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_TextU, -30 );
lv_obj_set_y( ui_TextU, 0 );
lv_obj_set_align( ui_TextU, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_TextU,"U");

ui_TextV = lv_label_create(ui_Voltage);
lv_obj_set_width( ui_TextV, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_TextV, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_TextV, 105 );
lv_obj_set_y( ui_TextV, 0 );
lv_obj_set_align( ui_TextV, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_TextV,"V");
lv_obj_set_style_text_font(ui_TextV, &ui_font_ASCII40MONO, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Current = lv_label_create(ui_InformationDock);
lv_obj_set_width( ui_Current, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Current, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Current, 2 );
lv_obj_set_y( ui_Current, -25 );
lv_obj_set_align( ui_Current, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_Current,"00.00");
lv_obj_set_style_text_color(ui_Current, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Current, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Current, &ui_font_ASCII40MONO, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_Current, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_Current, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_Text_Switch);
ui_object_set_themeable_style_property(ui_Current, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_Text_Switch);
lv_obj_set_style_border_color(ui_Current, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Current, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Current, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_Current, 32, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Current, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Current, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Current, -3, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TextI = lv_label_create(ui_Current);
lv_obj_set_width( ui_TextI, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_TextI, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_TextI, -30 );
lv_obj_set_y( ui_TextI, 0 );
lv_obj_set_align( ui_TextI, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_TextI,"I");

ui_TextA = lv_label_create(ui_Current);
lv_obj_set_width( ui_TextA, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_TextA, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_TextA, 105 );
lv_obj_set_y( ui_TextA, 0 );
lv_obj_set_align( ui_TextA, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_TextA,"A");
lv_obj_set_style_text_font(ui_TextA, &ui_font_ASCII40MONO, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Power = lv_label_create(ui_InformationDock);
lv_obj_set_width( ui_Power, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Power, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Power, 2 );
lv_obj_set_y( ui_Power, 26 );
lv_obj_set_align( ui_Power, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_Power,"000.0");
lv_obj_set_style_text_color(ui_Power, lv_color_hex(0x00FFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Power, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Power, &ui_font_ASCII40MONO, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_Power, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_Power, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_Text_Switch);
ui_object_set_themeable_style_property(ui_Power, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_Text_Switch);
lv_obj_set_style_border_color(ui_Power, lv_color_hex(0x00FFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Power, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Power, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_Power, 32, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Power, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Power, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Power, -3, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TextP = lv_label_create(ui_Power);
lv_obj_set_width( ui_TextP, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_TextP, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_TextP, -30 );
lv_obj_set_y( ui_TextP, 0 );
lv_obj_set_align( ui_TextP, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_TextP,"P");

ui_TextW = lv_label_create(ui_Power);
lv_obj_set_width( ui_TextW, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_TextW, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_TextW, 105 );
lv_obj_set_y( ui_TextW, 0 );
lv_obj_set_align( ui_TextW, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_TextW,"W");
lv_obj_set_style_text_font(ui_TextW, &ui_font_ASCII40MONO, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ImageWiFi = lv_img_create(ui_InformationDock);
lv_img_set_src(ui_ImageWiFi, &ui_img_1338783594);
lv_obj_set_width( ui_ImageWiFi, LV_SIZE_CONTENT);  /// 32
lv_obj_set_height( ui_ImageWiFi, LV_SIZE_CONTENT);   /// 32
lv_obj_set_x( ui_ImageWiFi, -2 );
lv_obj_set_y( ui_ImageWiFi, -10 );
lv_obj_set_align( ui_ImageWiFi, LV_ALIGN_BOTTOM_RIGHT );
lv_obj_add_flag( ui_ImageWiFi, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ImageWiFi, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Hour = lv_label_create(ui_InformationDock);
lv_obj_set_width( ui_Hour, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Hour, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Hour, 3 );
lv_obj_set_y( ui_Hour, 75 );
lv_obj_set_align( ui_Hour, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_Hour,"00");
ui_object_set_themeable_style_property(ui_Hour, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_Text_Switch);
ui_object_set_themeable_style_property(ui_Hour, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_Text_Switch);
lv_obj_set_style_text_font(ui_Hour, &ui_font_ASCII32MONO, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Minute = lv_label_create(ui_InformationDock);
lv_obj_set_width( ui_Minute, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Minute, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Minute, 51 );
lv_obj_set_y( ui_Minute, 75 );
lv_obj_set_align( ui_Minute, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_Minute,"00");
ui_object_set_themeable_style_property(ui_Minute, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_Text_Switch);
ui_object_set_themeable_style_property(ui_Minute, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_Text_Switch);
lv_obj_set_style_text_font(ui_Minute, &ui_font_ASCII32MONO, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Second = lv_label_create(ui_InformationDock);
lv_obj_set_width( ui_Second, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Second, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Second, 99 );
lv_obj_set_y( ui_Second, 75 );
lv_obj_set_align( ui_Second, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_Second,"00");
ui_object_set_themeable_style_property(ui_Second, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_Text_Switch);
ui_object_set_themeable_style_property(ui_Second, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_Text_Switch);
lv_obj_set_style_text_font(ui_Second, &ui_font_ASCII32MONO, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TextHM = lv_label_create(ui_InformationDock);
lv_obj_set_width( ui_TextHM, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_TextHM, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_TextHM, 35 );
lv_obj_set_y( ui_TextHM, -7 );
lv_obj_set_align( ui_TextHM, LV_ALIGN_BOTTOM_LEFT );
lv_label_set_text(ui_TextHM,":");
ui_object_set_themeable_style_property(ui_TextHM, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_Text_Switch);
ui_object_set_themeable_style_property(ui_TextHM, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_Text_Switch);
lv_obj_set_style_text_font(ui_TextHM, &ui_font_ASCII32MONO, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TextMS = lv_label_create(ui_InformationDock);
lv_obj_set_width( ui_TextMS, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_TextMS, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_TextMS, 83 );
lv_obj_set_y( ui_TextMS, -7 );
lv_obj_set_align( ui_TextMS, LV_ALIGN_BOTTOM_LEFT );
lv_label_set_text(ui_TextMS,":");
ui_object_set_themeable_style_property(ui_TextMS, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_Text_Switch);
ui_object_set_themeable_style_property(ui_TextMS, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_Text_Switch);
lv_obj_set_style_text_font(ui_TextMS, &ui_font_ASCII32MONO, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_USBADock = lv_obj_create(ui_MainScreen);
lv_obj_remove_style_all(ui_USBADock);
lv_obj_set_width( ui_USBADock, 64);
lv_obj_set_height( ui_USBADock, 48);
lv_obj_set_x( ui_USBADock, 2 );
lv_obj_set_y( ui_USBADock, 38 );
lv_obj_clear_flag( ui_USBADock, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_USBADock, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_USBADock, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_Container);
ui_object_set_themeable_style_property(ui_USBADock, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_Container);
lv_obj_set_style_border_color(ui_USBADock, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_USBADock, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_USBADock, 2, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ImageUSBA = lv_img_create(ui_USBADock);
lv_img_set_src(ui_ImageUSBA, &ui_img_2092987087);
lv_obj_set_width( ui_ImageUSBA, LV_SIZE_CONTENT);  /// 32
lv_obj_set_height( ui_ImageUSBA, LV_SIZE_CONTENT);   /// 32
lv_obj_set_x( ui_ImageUSBA, 0 );
lv_obj_set_y( ui_ImageUSBA, -6 );
lv_obj_set_align( ui_ImageUSBA, LV_ALIGN_TOP_MID );
lv_obj_add_flag( ui_ImageUSBA, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ImageUSBA, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_VoltageUSBA = lv_label_create(ui_USBADock);
lv_obj_set_width( ui_VoltageUSBA, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_VoltageUSBA, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_VoltageUSBA, 0 );
lv_obj_set_y( ui_VoltageUSBA, 8 );
lv_obj_set_align( ui_VoltageUSBA, LV_ALIGN_CENTER );
lv_label_set_text(ui_VoltageUSBA,"00.0V");
ui_object_set_themeable_style_property(ui_VoltageUSBA, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_Text_Switch);
ui_object_set_themeable_style_property(ui_VoltageUSBA, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_Text_Switch);
lv_obj_set_style_text_font(ui_VoltageUSBA, &ui_font_ASCII20MONO, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_USBC3Dock = lv_obj_create(ui_MainScreen);
lv_obj_remove_style_all(ui_USBC3Dock);
lv_obj_set_width( ui_USBC3Dock, 64);
lv_obj_set_height( ui_USBC3Dock, 48);
lv_obj_set_x( ui_USBC3Dock, 2 );
lv_obj_set_y( ui_USBC3Dock, 89 );
lv_obj_clear_flag( ui_USBC3Dock, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_USBC3Dock, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_USBC3Dock, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_Container);
ui_object_set_themeable_style_property(ui_USBC3Dock, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_Container);
lv_obj_set_style_border_color(ui_USBC3Dock, lv_color_hex(0x00FFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_USBC3Dock, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_USBC3Dock, 2, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ImageUSBC3 = lv_img_create(ui_USBC3Dock);
lv_img_set_src(ui_ImageUSBC3, &ui_img_426970754);
lv_obj_set_width( ui_ImageUSBC3, LV_SIZE_CONTENT);  /// 32
lv_obj_set_height( ui_ImageUSBC3, LV_SIZE_CONTENT);   /// 32
lv_obj_set_x( ui_ImageUSBC3, 0 );
lv_obj_set_y( ui_ImageUSBC3, -6 );
lv_obj_set_align( ui_ImageUSBC3, LV_ALIGN_TOP_MID );
lv_obj_add_flag( ui_ImageUSBC3, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ImageUSBC3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_VoltageUSBC3 = lv_label_create(ui_USBC3Dock);
lv_obj_set_width( ui_VoltageUSBC3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_VoltageUSBC3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_VoltageUSBC3, 0 );
lv_obj_set_y( ui_VoltageUSBC3, 8 );
lv_obj_set_align( ui_VoltageUSBC3, LV_ALIGN_CENTER );
lv_label_set_text(ui_VoltageUSBC3,"00.0V");
ui_object_set_themeable_style_property(ui_VoltageUSBC3, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_Text_Switch);
ui_object_set_themeable_style_property(ui_VoltageUSBC3, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_Text_Switch);
lv_obj_set_style_text_font(ui_VoltageUSBC3, &ui_font_ASCII20MONO, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_USBC2Dock = lv_obj_create(ui_MainScreen);
lv_obj_remove_style_all(ui_USBC2Dock);
lv_obj_set_width( ui_USBC2Dock, 64);
lv_obj_set_height( ui_USBC2Dock, 48);
lv_obj_set_x( ui_USBC2Dock, 2 );
lv_obj_set_y( ui_USBC2Dock, 140 );
lv_obj_clear_flag( ui_USBC2Dock, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_USBC2Dock, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_USBC2Dock, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_Container);
ui_object_set_themeable_style_property(ui_USBC2Dock, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_Container);
lv_obj_set_style_border_color(ui_USBC2Dock, lv_color_hex(0x00FFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_USBC2Dock, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_USBC2Dock, 2, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ImageUSBC2 = lv_img_create(ui_USBC2Dock);
lv_img_set_src(ui_ImageUSBC2, &ui_img_426970754);
lv_obj_set_width( ui_ImageUSBC2, LV_SIZE_CONTENT);  /// 32
lv_obj_set_height( ui_ImageUSBC2, LV_SIZE_CONTENT);   /// 32
lv_obj_set_x( ui_ImageUSBC2, 0 );
lv_obj_set_y( ui_ImageUSBC2, -6 );
lv_obj_set_align( ui_ImageUSBC2, LV_ALIGN_TOP_MID );
lv_obj_add_flag( ui_ImageUSBC2, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ImageUSBC2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_ImageUSBC2Fast = lv_img_create(ui_USBC2Dock);
lv_img_set_src(ui_ImageUSBC2Fast, &ui_img_175199537);
lv_obj_set_width( ui_ImageUSBC2Fast, LV_SIZE_CONTENT);  /// 16
lv_obj_set_height( ui_ImageUSBC2Fast, LV_SIZE_CONTENT);   /// 16
lv_obj_set_x( ui_ImageUSBC2Fast, 23 );
lv_obj_set_y( ui_ImageUSBC2Fast, -11 );
lv_obj_set_align( ui_ImageUSBC2Fast, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ImageUSBC2Fast, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ImageUSBC2Fast, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_VoltageUSBC2 = lv_label_create(ui_USBC2Dock);
lv_obj_set_width( ui_VoltageUSBC2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_VoltageUSBC2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_VoltageUSBC2, 0 );
lv_obj_set_y( ui_VoltageUSBC2, 8 );
lv_obj_set_align( ui_VoltageUSBC2, LV_ALIGN_CENTER );
lv_label_set_text(ui_VoltageUSBC2,"00.0V");
ui_object_set_themeable_style_property(ui_VoltageUSBC2, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_Text_Switch);
ui_object_set_themeable_style_property(ui_VoltageUSBC2, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_Text_Switch);
lv_obj_set_style_text_font(ui_VoltageUSBC2, &ui_font_ASCII20MONO, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_USBC1Dock = lv_obj_create(ui_MainScreen);
lv_obj_remove_style_all(ui_USBC1Dock);
lv_obj_set_width( ui_USBC1Dock, 64);
lv_obj_set_height( ui_USBC1Dock, 48);
lv_obj_set_x( ui_USBC1Dock, 2 );
lv_obj_set_y( ui_USBC1Dock, 191 );
lv_obj_clear_flag( ui_USBC1Dock, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_USBC1Dock, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_USBC1Dock, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_Container);
ui_object_set_themeable_style_property(ui_USBC1Dock, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_Container);
lv_obj_set_style_border_color(ui_USBC1Dock, lv_color_hex(0x00FFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_USBC1Dock, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_USBC1Dock, 2, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ImageUSBC1 = lv_img_create(ui_USBC1Dock);
lv_img_set_src(ui_ImageUSBC1, &ui_img_426970754);
lv_obj_set_width( ui_ImageUSBC1, LV_SIZE_CONTENT);  /// 32
lv_obj_set_height( ui_ImageUSBC1, LV_SIZE_CONTENT);   /// 32
lv_obj_set_x( ui_ImageUSBC1, 0 );
lv_obj_set_y( ui_ImageUSBC1, -6 );
lv_obj_set_align( ui_ImageUSBC1, LV_ALIGN_TOP_MID );
lv_obj_add_flag( ui_ImageUSBC1, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ImageUSBC1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_ImageUSBC1Fast = lv_img_create(ui_USBC1Dock);
lv_img_set_src(ui_ImageUSBC1Fast, &ui_img_175199537);
lv_obj_set_width( ui_ImageUSBC1Fast, LV_SIZE_CONTENT);  /// 16
lv_obj_set_height( ui_ImageUSBC1Fast, LV_SIZE_CONTENT);   /// 16
lv_obj_set_x( ui_ImageUSBC1Fast, 23 );
lv_obj_set_y( ui_ImageUSBC1Fast, -11 );
lv_obj_set_align( ui_ImageUSBC1Fast, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ImageUSBC1Fast, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ImageUSBC1Fast, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_VoltageUSBC1 = lv_label_create(ui_USBC1Dock);
lv_obj_set_width( ui_VoltageUSBC1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_VoltageUSBC1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_VoltageUSBC1, 0 );
lv_obj_set_y( ui_VoltageUSBC1, 8 );
lv_obj_set_align( ui_VoltageUSBC1, LV_ALIGN_CENTER );
lv_label_set_text(ui_VoltageUSBC1,"00.0V");
ui_object_set_themeable_style_property(ui_VoltageUSBC1, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_Text_Switch);
ui_object_set_themeable_style_property(ui_VoltageUSBC1, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_Text_Switch);
lv_obj_set_style_text_font(ui_VoltageUSBC1, &ui_font_ASCII20MONO, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_USBCSwitch, ui_event_USBCSwitch, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_USBASwitch, ui_event_USBASwitch, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Setting, ui_event_Setting, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Weather, ui_event_Weather, LV_EVENT_ALL, NULL);

}
